apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    tier: backend
  ports:
    - port: 8080
      targetPort: 8080
  clusterIP: None  # optional: make headless for service discovery or use `ClusterIP`
