apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
      - name: backend
        image: gcr.io/YOUR_PROJECT_ID/backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: 127.0.0.1
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password

      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.33.0
        command: ["/cloud_sql_proxy",
                  "-instances=PROJECT_ID:REGION:mysql-db=tcp:3306",
                  "-credential_file=/secrets/service_account.json"]
        volumeMounts:
        - name: sql-creds
          mountPath: /secrets
          readOnly: true

      volumes:
      - name: sql-creds
        secret:
          secretName: cloudsql-instance-credentials
